# Generated by Django 5.1.3 on 2024-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=20),
        ),
    ]
